### ISSUE TITLE
Sign Assembly

### ISSUE THREAD

**Issue by emdadgar2** [OmerMor/AsyncBridge#5]
Hi,
Please sign Nuget package to easier use...
Thanks

**Comment by alexdavies74** [comment]
I don't have a windows machine available anymore to do this. If anyone still wants it, I can make you an owner of the nuget project.

**Comment by falahati** [comment]
@jspraul, it does.
Currently using Microsoft.Bcl.Async with VS2015 to target Windows XP and it works. But there are some problems. Firstly, all clients need to install two updates for .Net 4 and they should have Windows XP SP3 (or x64 SP2) to do so. Also you need to ship the config file side by side of the application (which of course is not a problem by it-self). Yet I still had some difficultly with Mono port of the application. Honestly, I could have wrote the app using old API and even save some time.

I am going to test this project in next days and will report of its success.

**Comment by hypersw** [comment]
Unfortunately, the `Microsoft.Bcl.Async` package is incomplete in that it references missing assemblies  like `System.Threading.Tasks, Version=1.5.11.0` which is nowhere to be found for target framework .NET 4 (there're DLLs of the same version for different frameworks and the set of classes in them does not match the requirements). I couldn't make a working set out of it. So we're using this AsyncBridge, and had to sign the DLL with our key to make it load in or strongnamed environment.

**Comment by jnm2** [comment]
AsyncBridge.Net35 and AsyncBridge.Portable have been signed since 2012-04-27. Unlike those two, a 0.2.0 of AsyncBridge was never published and so there has never been a signed package for.NET Framework 4.0.

Since this issue was filed in 2014, the OP must have been asking about the .NET Framework 4.0 package and therefore [Alex's comment](https://github.com/OmerMor/AsyncBridge/issues/5#issuecomment-36171815) applies– try using https://www.nuget.org/packages/Microsoft.Bcl.Async should be used on .NET Framework 4.0.

For those who are actually on .NET Framework 3.5, you've already had the signed `AsyncBridge.Net35` since 2012.

However, looking forward: I am going to correct the inconsistency by publishing a new `AsyncBridge` package to fill the gap for the net40 build, even though we still recommend using Microsoft.Bcl.Async instead since you're on net40.

**Comment by jnm2** [comment]
The latest versions of all AsyncBridge packages contain only signed DLLs.

Newly unified package (net35, net40 and sl5):  
[![NuGet](https://img.shields.io/nuget/v/AsyncBridge.svg)](https://www.nuget.org/packages/AsyncBridge/) 

Deprecated packages:  
[![NuGet](https://img.shields.io/nuget/v/AsyncBridge.Net35.svg)](https://www.nuget.org/packages/AsyncBridge.Net35/) <sup>(AsyncBridge.Net35)</sup>  
[![NuGet](https://img.shields.io/nuget/v/AsyncBridge.Portable.svg)](https://www.nuget.org/packages/AsyncBridge.Portable/) <sup>(AsyncBridge.Portable)</sup>
